version: "3.5"

networks:
        inception:
                name: inception-net

volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: /home/ebalgruu/data/wordpress
                        o: bind
                        type: none
        mariadb:
                name: mariadb
                driver: local
                driver_opts:
                        device: /home/ebalgruu/data/mariadb
                        o: bind
                        type: none
        website:
                name: website
                driver: local
                driver_opts:
                        device: /home/ebalgruu/data/html
                        o: bind
                        type: none
        portainer:
                name: portainer
                driver: local
                driver_opts:
                        device: /home/ebalgruu/data/portainer
                        o: bind
                        type: none

services:
        nginx:
                container_name: nginx
                build: ./requirements/nginx
                image: nginx
                ports:
                        - "443:443"
                volumes:
                        - wordpress:/var/www/wordpress
                        - website:/var/www/html
                networks:
                        - inception
                restart: always
                depends_on:
                        - wordpress
        mariadb:  
                container_name: mariadb
                build: ./requirements/mariadb
                image: mariadb
                volumes:
                        - mariadb:/var/lib/mysql
                networks:
                        - inception
                env_file: .env
                restart: always
        wordpress:
                container_name: wordpress
                build: ./requirements/wordpress
                image: wordpress
                ports:
                        - "9000:9000"
                volumes:
                        - wordpress:/var/www/wordpress
                networks:
                        - inception
                restart: always
                env_file: .env
                depends_on:
                        - mariadb
        ftp-server:
                container_name: ftp-server
                build: ./requirements/bonus/ftp-server
                image: ftp-server
                ports:
                        - "21:21"
                        - "40000-40010:40000-40010"
                volumes:
                        - /home/ebalgruu/data/:/var/www/ftp
                networks:
                        - inception
                restart: always
                env_file: .env
                depends_on:
                        - wordpress
        portainer:
                container_name: portainer
                build: ./requirements/bonus/portainer
                image: portainer
                ports:
                        - "8000:9000"
                        - "9443:9443"
                volumes:
                        - /etc/localtime:/etc/localtime
                        - portainer:/data
                        - /var/run/docker.sock:/var/run/docker.sock
                networks:
                        - inception
                restart: always
        adminer:
                container_name: adminer
                build: ./requirements/bonus/adminer
                image: adminer
                ports:
                        - 8080:8080
                networks:
                        - inception
                restart: always
                depends_on:
                        - mariadb
        redis:
                container_name: redis
                build: ./requirements/bonus/redis
                image: redis
                ports:
                        - "6379:6379"
                networks:
                        - inception
                restart: always